# Generated by Django 3.0.5 on 2020-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B7data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40, null=True)),
                ('surface', models.CharField(blank=True, max_length=40, null=True)),
                ('shadowing', models.CharField(blank=True, max_length=5, null=True)),
                ('combined1', models.IntegerField(default=0)),
                ('combined2', models.IntegerField(default=0)),
                ('combined3', models.IntegerField(default=0)),
                ('SpecialCom', models.IntegerField(default=0)),
                ('Swing', models.IntegerField(default=0)),
                ('slid', models.IntegerField(default=0)),
                ('carrousel', models.IntegerField(default=0)),
                ('spring', models.IntegerField(default=0)),
                ('omega', models.IntegerField(default=0)),
                ('roserose', models.IntegerField(default=0)),
                ('other', models.CharField(blank=True, max_length=40, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
            ],
        ),
    ]
