# Generated by Django 3.0.5 on 2020-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkapp', '0002_b7data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b7data',
            name='shadowing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
