# Generated by Django 3.0.5 on 2020-05-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parkapp', '0003_auto_20200502_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parkimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='park_pics')),
                ('park', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Parkapp.B7data')),
            ],
        ),
    ]
