# Generated by Django 3.0.5 on 2020-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkapp', '0005_parent_childs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkimg',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='park_pics'),
        ),
    ]
